import streamlit as st


def draw_bar(label: str, pct: int, fill_class: str):
    st.markdown(
        f"""
        <div class='bar-row'>
            <div class='bar-label'>{label}</div>
            <div class='bar-bg'>
                <div class='{fill_class}' style='width:{pct}%;'></div>
            </div>
            <div class='bar-pct'>{pct}%</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_explanation_page(state):
    st.markdown("## Why this recommendation?")

    e1, e2 = st.columns([1.1, 1])

    with e1:
        st.markdown("<div class='inner-card'>", unsafe_allow_html=True)
        st.markdown("**Top Contributing Features (LLM-generated)**")

        contributions = state.get("feature_importance_without_sensitive", {})
        color_cycle = [
            "bar-fill-blue",
            "bar-fill-green",
            "bar-fill-pink",
            "bar-fill-orange",
            "bar-fill-gray",
        ]

        for i, (label, pct) in enumerate(
            sorted(contributions.items(), key=lambda x: x[1], reverse=True)
        ):
            draw_bar(label, pct, color_cycle[i % len(color_cycle)])

        st.markdown("</div>", unsafe_allow_html=True)

    with e2:
        st.markdown("<div class='inner-card'>", unsafe_allow_html=True)
        st.markdown("**Explanation**")
        st.write(state["ai_explanation"])
        st.markdown("</div>", unsafe_allow_html=True)

    st.markdown(
        "<div class='help-box'>This page shows case-specific feature importance generated by the LLM for the non-sensitive recommendation path.</div>",
        unsafe_allow_html=True,
    )